### ISSUE TITLE
Unicode displaying in dataset descriptions

### ISSUE THREAD

**Issue by dandanxu** [solvebio/solvebio-python#56] opened 2014-11-05 16:47 UTC
- when I do look at, for example, clinvar_phenotypes.fields(), the apostrophes come out as \u2019

```
clinvar_phenotypes = solvebio.Dataset.retrieve('ClinVar/2.0.0-1/Phenotypes')
clinvar_phenotypes.fields()
{
      "class_name": "DatasetField", 
      "created_at": "2014-07-24T01:06:08Z", 
      "data_type": "string", 
      "dataset": "ClinVar/2.0.0-1/Phenotypes", 
      "dataset_id": 23, 
      "description": "A universally unique identifier containing the variant\u2019s RCV Accession Number and GRC human reference assembly.", 
      "facets_url": "https://api.solvebio.com/v1/dataset_fields/673/facets", 
      "full_name": "ClinVar/2.0.0-1/Phenotypes/uuid", 
      "id": 673, 
      "name": "uuid", 
      "updated_at": "2014-07-24T23:13:24.547Z", 
      "url": "https://api.solvebio.com/v1/dataset_fields/673"
    }
```

**Comment by davecap** [comment] 2016-01-14 17:41
Closing this because we can't seem to reproduce it anymore. @dandanxu if you can reproduce it please post an example.

**Closed by davecap** 2016-01-14 17:41 UTC
Labels: bug, P1:high
